weather/urls.py
from django.urls import path

from .views import index, info

app_name = 'weather'
urlpatterns = [
    path('', index, name='index'),
    path('<city>', info, name='info')
]

weather_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls'))
]

weather/views.py
from django.shortcuts import render, redirect
from django.urls import NoReverseMatch

from .weather_check import hyper_weather_check


def index(requests):
    if requests.POST:
        try:
            return redirect('weather:info', requests.POST['text'])
        except NoReverseMatch:
            return render(requests, 'weather/index.html')
    return render(requests, 'weather/index.html')


def info(requests, city):
    city_info = hyper_weather_check(city)
    try:
        context = {
            'city_now': city_info['now'],
            'city_hourly': city_info['hourly'],
            'city_daily': city_info['daily'],
        }
        return render(requests, 'weather/info.html', context=context)
    except KeyError:
        context = {
            'error': 'Ошибка: Введенные данные некорректны'
        }
        return render(requests, 'weather/info.html', context=context)

weather/templates/weather/basefooter.html
<footer class="pt-4 my-md-5 pt-md-5 border-top text-center">
        <div class="col-6 col-md">
            <h5>КОНТАКТЫ</h5>
            <ul class="list-unstyled text-small">
                <li><a href="https://www.linkedin.com/in/владислав-шинкарьов-25b53a1b6/" class="text-muted">Linkedin</a>
                </li>
                <li>E-mail: RoyalSam@ukr.net</li>
                <li>Номер телефона: (068)-90-07-931</li>
            </ul>
        </div>
    <div class="col-6 col-md">
            <h5>Использую API <a href="https://openweathermap.org" class="text-muted">OpenWeatherMap</a></h5>
        </div>

</footer>

weather/templates/weather/basehead.html
{% load static %}
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'weather:index' %}">
    <img src="{% static 'fav_ico/Papirus-Team-Papirus-Apps-Weather.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    Weather
  </a>
</nav>

weather/templates/weather/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'fav_ico/weather_32x32.ico' %}"/>

    <script src="{% static "vendor/js/jquery-3.3.1.slim.min.js" %}" defer></script>

    <script src="{% static "vendor/js/popper.min.js" %}" async></script>

    <link rel="stylesheet" href="{% static "vendor/css/bootstrap.min.css" %}">

    <script src="{% static "vendor/js/bootstrap.min.js" %}" defer></script>
    <meta charset="UTF-8">
    <title>Погода</title>
</head>
<body>
{% include 'weather/basehead.html' %}
<div class="container">
    <div class="jumbotron mt-3">
        <h1 class="display-4">Погода</h1>
        <p class="lead">Что бы узнать погоду в вашем городе вам нужно ввести название в следующем поле</p>
        <hr class="my-4">
        <form action="." method="post"> {% csrf_token %}
            <label for="city">Название города</label>
            <input type="text" class="form-control" id="city" name="text">
            <hr class="my-4">
            <input type="submit" name="ask" class="btn btn-primary btn-lg" value="Узнать погоду">
        </form>
    </div>
    {% include 'weather/basefooter.html' %}
</div>

</body>
</html>

weather/templates/weather/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'fav_ico/weather_32x32.ico' %}"/>

    <script src="{% static "vendor/js/jquery-3.3.1.slim.min.js" %}" defer></script>

    <script src="{% static "vendor/js/popper.min.js" %}" async></script>

    <link rel="stylesheet" href="{% static "vendor/css/bootstrap.min.css" %}">

    <script src="{% static "vendor/js/bootstrap.min.js" %}" defer></script>
    <meta charset="UTF-8">
    <title>Детальная информация</title>
</head>
<body>
{% include 'weather/basehead.html' %}
<div class="container">
    {% if error %}
        <div class="alert alert-danger mt-3" role="alert">
            {{ error }}
        </div>
        <a class="btn btn-primary btn-lg" href="{% url 'weather:index' %}">Вернутся на главную</a>
    {% else %}
        <div class="jumbotron mt-3">
            {% include 'weather/weather_description.html' %}
            <h1 class="display-4">Погода {{ city_now.city_name }}</h1>
            <h3 class="display-4">Температура: {{ city_now.weather_temp }}°С</h3>
            <h2 class="lead">Чувтсвуется как: {{ city_now.weather_feels_temp }}°С</h2>
            <h2 class="lead">Скорость ветра: {{ city_now.wind_speed }}</h2>
            <h2 class="lead">{{ city_now.weather_description }}</h2>
            <hr class="my-4">
            <h1 class="display-4 text-center">Более детальная информация</h1>
            <div id="accordion">
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h5 class="mb-0">
                            <button class="btn btn-light btn-lg" data-toggle="collapse" data-target="#collapseOne"
                                    aria-expanded="true" aria-controls="collapseOne">
                                Погода до конца дня
                            </button>
                        </h5>
                    </div>
                    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                        <div class="row">
                            {% for city_now in city_hourly.values %}
                                <div class="col-sm-12 col-lg-6 pb-2">

                                    <div class="card h-100 shadow">
                                        {% include 'weather/weather_description.html' %}
                                        <div class="card-body">
                                            <h1>Температура: {{ city_now.temp_day }}°С</h1>
                                            <p>Чувсвуется как: {{ city_now.feels_temp_day }}°С</p>
                                            <p>Скорость ветра: {{ city_now.wind_speed }}</p>
                                            <p>{{ city_now.weather_description }}</p>
                                        </div>
                                        <div class="card-footer">
                                            <h1>{{ city_now.time }}</h1>
                                        </div>
                                    </div>
                                </div>

                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingTwo">
                        <h5 class="mb-0">
                            <button class="btn btn-light btn-lg collapsed" data-toggle="collapse"
                                    data-target="#collapseTwo"
                                    aria-expanded="false" aria-controls="collapseTwo">
                                Погода на неделю вперед
                            </button>
                        </h5>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                        <div class="row">
                            {% for city_now in city_daily.values %}
                                <div class="col-sm-12 col-lg-6 pb-2">

                                    <div class="card h-100 shadow">
                                        {% include 'weather/weather_description.html' %}
                                        <div class="card-body">
                                            <div class="text-center">
                                                <h1>Температура</h1>
                                            </div>
                                            <div class="row d-flex justify-content-around">
                                                <h2>Утром</h2>
                                                <h2>Днем</h2>
                                            </div>
                                            <div class="row d-flex justify-content-around">
                                                <h2>{{ city_now.temp_morn }}°С</h2>
                                                <h2>{{ city_now.temp_day }}°С</h2>

                                            </div>
                                            <hr class="my-4">
                                            <div class="row d-flex justify-content-around">
                                                <h2>Вечером</h2>
                                                <h2>Ночью</h2>
                                            </div>
                                            <div class="row d-flex justify-content-around">
                                                <h2>{{ city_now.temp_eve }}°С</h2>
                                                <h2>{{ city_now.temp_night }}°С</h2>
                                            </div>
                                            <hr class="my-4">
                                            <div class="text-center">
                                                <h3>Чувствуется как</h3>
                                            </div>
                                            <div class="row d-flex justify-content-around">
                                                <h2>Утром</h2>
                                                <h2>Днем</h2>
                                            </div>
                                            <div class="row d-flex justify-content-around">
                                                <h2>{{ city_now.feels_temp_morn }}°С</h2>
                                                <h2>{{ city_now.feels_temp_day }}°С</h2>

                                            </div>
                                            <hr class="my-4">
                                            <div class="row d-flex justify-content-around">
                                                <h2>Вечером</h2>
                                                <h2>Ночью</h2>
                                            </div>
                                            <div class="row d-flex justify-content-around">
                                                <h2>{{ city_now.feels_temp_eve }}°С</h2>
                                                <h2>{{ city_now.feels_temp_night }}°С</h2>
                                            </div>
                                        </div>
                                        <hr class="my-4">
                                        <div class="text-center pb-3">
                                            <h3>{{ city_now.weather_description }}</h3>
                                        </div>
                                        <div class="card-footer">
                                            <h1>{{ city_now.day_of_week }}</h1>
                                        </div>
                                    </div>
                                </div>

                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    {% include 'weather/basefooter.html' %}
</div>
</body>
</html>

weather/templates/weather/weather_description.html
{% load static %}
{% if city_now.weather_description == 'Ясно' %}
    <img src="{% static 'images/01d@2x.png' %}" class="float-right rounded-circle shadow bg-white ml-3 mt-3"
         alt="{{ weather_description }}" width="100"
         height="100">
{% elif city_now.weather_description == 'Облачно с прояснениями' %}
    <img src="{% static 'images/02d@2x.png' %}" class="float-right rounded-circle shadow bg-white  ml-3 mt-3"
         alt="{{ weather_description }}" width="100"
         height="100">
{% elif city_now.weather_description == 'Переменная облачность' %}
    <img src="{% static 'images/03d@2x.png' %}" class="float-right rounded-circle shadow bg-white  ml-3 mt-3"
         alt="{{ weather_description }}" width="100"
         height="100">
{% elif city_now.weather_description == 'Небольшая облачность' %}
    <img src="{% static 'images/03d@2x.png' %}" class="float-right rounded-circle shadow bg-white  ml-3 mt-3"
         alt="{{ weather_description }}" width="100"
         height="100">
{% elif city_now.weather_description == 'Пасмурно' %}
    <img src="{% static 'images/04d@2x.png' %}" class="float-right rounded-circle shadow bg-white ml-3 mt-3"
         alt="{{ weather_description }}" width="100"
         height="100">
{% elif city_now.weather_description == 'Небольшой дождь' %}
    <img src="{% static 'images/09d@2x.png' %}" class="float-right rounded-circle shadow bg-white ml-3 mt-3"
         alt="{{ weather_description }}" width="100"
         height="100">
    {% elif city_now.weather_description == 'Небольшой проливной дождь' %}
    <img src="{% static 'images/09d@2x.png' %}" class="float-right rounded-circle shadow bg-white ml-3 mt-3"
         alt="{{ weather_description }}" width="100"
         height="100">
{% elif city_now.weather_description == 'Дождь' %}
    <img src="{% static 'images/10d@2x.png' %}" class="float-right rounded-circle shadow bg-white  ml-3 mt-3"
         alt="{{ weather_description }}" width="100"
         height="100">
{% elif city_now.weather_description == 'Сильный дождь' %}
    <img src="{% static 'images/11d@2x.png' %}" class="float-right rounded-circle shadow bg-white  ml-3 mt-3"
         alt="{{ weather_description }}" width="100"
         height="100">
{% endif %}